import streamlit as st
from groq import Groq
import os
from dotenv import load_dotenv
import PyPDF2
import pandas as pd
from fpdf import FPDF
import datetime
import plotly.express as px

load_dotenv()
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

st.set_page_config(
    page_title="AI Business Assistant",
    page_icon="💼",
    layout="wide",
    initial_sidebar_state="expanded"
)
bg = "#0f1117"
text = "#ffffff"
card_bg = "#1e2130"
sidebar_bg = "#1e2130"

st.markdown(f"""
<style>
    .stApp {{ background-color: {bg}; color: {text}; }}
    .stChatMessage {{ background-color: {card_bg}; border-radius: 10px; padding: 10px; margin: 5px 0; }}
    .stSidebar {{ background-color: {sidebar_bg}; }}
    section.main > div {{ padding-bottom: 80px; }}
    .metric-card {{
        background-color: {card_bg};
        border-radius: 10px;
        padding: 15px;
        text-align: center;
        border: 1px solid #2e3250;
    }}
    .status-box {{
        background-color: #1a3a2a;
        border-left: 4px solid #00c853;
        padding: 10px;
        border-radius: 5px;
        margin: 5px 0;
    }}
    h1 {{ color: #4da6ff !important; }}
    .stButton>button {{
        border-radius: 8px;
        border: none;
        width: 100%;
    }}
</style>
""", unsafe_allow_html=True)

# session states
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": "👋 Hello! I'm your AI Business Assistant powered by LLaMA 3.\n\nI can help you with:\n- 📄 **Document Analysis** (upload PDF/Excel)\n- 📈 **Business Strategy**\n- 💡 **Sales & Marketing Tips**\n- 📊 **Data Insights**\n\nHow can I help you today?"}
    ]
if "doc_text" not in st.session_state:
    st.session_state.doc_text = ""
if "doc_names" not in st.session_state:
    st.session_state.doc_names = []
if "query_count" not in st.session_state:
    st.session_state.query_count = 0
if "docs_uploaded" not in st.session_state:
    st.session_state.docs_uploaded = 0
if "excel_df" not in st.session_state:
    st.session_state.excel_df = None

# extract functions
def extract_pdf_text(file):
    reader = PyPDF2.PdfReader(file)
    text = ""
    for page in reader.pages:
        text += page.extract_text()
    return text

def extract_excel_text(file):
    df = pd.read_excel(file)
    st.session_state.excel_df = df
    return df.to_string()

def export_chat_pdf():
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "AI Business Assistant - Chat Export", ln=True, align="C")
    pdf.set_font("Helvetica", size=8)
    pdf.cell(0, 8, f"Exported: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align="C")
    pdf.ln(5)
    pdf.set_font("Helvetica", size=10)
    for msg in st.session_state.messages:
        role = "You" if msg["role"] == "user" else "Assistant"
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 8, f"{role}:", ln=True)
        pdf.set_font("Helvetica", size=9)
        clean_text = msg["content"].encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 6, clean_text)
        pdf.ln(3)
    return pdf.output()

# ---------------- EMAIL SEND FUNCTION ----------------
def send_email_gmail(to_email, company_name):
    """Sends chat summary email through Gmail."""
    try:
        import smtplib
        from email.mime.text import MIMEText
        from email.mime.multipart import MIMEMultipart

        sender = os.getenv("EMAIL_ADDRESS")
        password = os.getenv("EMAIL_PASSWORD")

        if not sender or not password:
            return False, "❌ EMAIL_ADDRESS or EMAIL_PASSWORD not found in .env file!"

        now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')

        body = f"""
{'='*60}
  AI BUSINESS ASSISTANT - CHAT SUMMARY
{'='*60}

📅 Date: {now}
🏢 Company: {company_name if company_name else 'N/A'}
💬 Total Messages: {len(st.session_state.messages)}
📄 Documents Uploaded: {st.session_state.docs_uploaded}

{'='*60}
  CONVERSATION
{'='*60}

"""
        for i, m in enumerate(st.session_state.messages, 1):
            role = "👤 YOU" if m['role'] == 'user' else "🤖 AI ASSISTANT"
            body += f"\n{role} (Message {i}):\n{m['content']}\n{'-'*60}\n"

        body += f"""
{'='*60}
  Generated by AI Business Assistant
  Powered by LLaMA 3 | Groq API
{'='*60}
"""

        msg = MIMEMultipart()
        msg['From'] = sender
        msg['To'] = to_email
        msg['Subject'] = f"AI Business Assistant - Chat Summary | {company_name if company_name else 'Report'} | {now}"
        msg.attach(MIMEText(body, 'plain'))

        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender, password)
        server.send_message(msg)
        server.quit()

        return True, "✅ Email sent successfully!"

    except smtplib.SMTPAuthenticationError:
        return False, "❌ Gmail login failed! Check EMAIL_ADDRESS and EMAIL_PASSWORD in .env file. Use App Password, not normal password!"

    except smtplib.SMTPException as e:
        return False, f"❌ SMTP Error: {str(e)}"

    except Exception as e:
        return False, f"❌ Error: {str(e)}"

# -----------------------------------------------------

if "dark_mode" not in st.session_state:
    st.session_state.dark_mode = True

col1, col2 = st.columns([3, 1])
with col1:
    st.title("💼 AI Business Assistant")
    st.caption("Powered by LLaMA 3 • Smart • Fast • Professional")
with col2:
    st.markdown("<br>", unsafe_allow_html=True)
    if st.button("📥 Export Chat PDF"):
        pdf_bytes = export_chat_pdf()
        st.download_button(
            label="⬇️ Download Now",
            data=bytes(pdf_bytes),
            file_name=f"chat_export_{datetime.datetime.now().strftime('%Y%m%d_%H%M')}.pdf",
            mime="application/pdf"
        )
st.divider()

# analytics
st.markdown("### 📊 Analytics")
c1, c2, c3 = st.columns(3)
with c1:
    st.markdown(f"""<div class="metric-card"><h2 style="color:#4da6ff">{st.session_state.query_count}</h2><p>Queries Answered</p></div>""", unsafe_allow_html=True)
with c2:
    st.markdown(f"""<div class="metric-card"><h2 style="color:#00c853">{st.session_state.docs_uploaded}</h2><p>Documents Uploaded</p></div>""", unsafe_allow_html=True)
with c3:
    st.markdown(f"""<div class="metric-card"><h2 style="color:#ff9800">{len(st.session_state.messages)}</h2><p>Total Messages</p></div>""", unsafe_allow_html=True)
st.divider()

# -------------- CHART SECTION --------------
if st.session_state.get("excel_df") is not None:
    df = st.session_state.excel_df
    st.markdown("### 📊 Excel Data Chart")
    col_a, col_b, col_c = st.columns(3)
    with col_a:
        chart_type = st.selectbox("Chart Type", ["Bar", "Line", "Pie"], key="chart_type")
    with col_b:
        x_col = st.selectbox("X Axis", df.columns.tolist(), key="x_col")
    with col_c:
        y_col = st.selectbox("Y Axis", df.select_dtypes(include='number').columns.tolist(), key="y_col")

    if chart_type == "Bar":
        fig = px.bar(df, x=x_col, y=y_col, title=f"{y_col} by {x_col}")
    elif chart_type == "Line":
        fig = px.line(df, x=x_col, y=y_col, title=f"{y_col} over {x_col}")
    elif chart_type == "Pie":
        fig = px.pie(df, names=x_col, values=y_col, title=f"{y_col} by {x_col}")

    fig.update_layout(paper_bgcolor="#1e2130", plot_bgcolor="#1e2130", font_color="#ffffff")
    st.plotly_chart(fig, use_container_width=True)
    st.divider()

# -------------- SIDEBAR --------------
with st.sidebar:
    st.markdown("### ⚙️ Settings")
    st.divider()

    st.markdown("### 📂 Document Upload")
    uploaded_files = st.file_uploader(
        "Upload PDF or Excel (Multiple)",
        type=["pdf", "xlsx"],
        accept_multiple_files=True,
        help="Upload multiple business documents!"
    )

    if uploaded_files:
        all_text = ""
        names = []
        for file in uploaded_files:
            with st.spinner(f"Reading {file.name}..."):
                if file.name.endswith(".pdf"):
                    all_text += extract_pdf_text(file) + "\n\n"
                else:
                    all_text += extract_excel_text(file) + "\n\n"
                names.append(file.name)
        st.session_state.doc_text = all_text
        st.session_state.doc_names = names
        st.session_state.docs_uploaded = len(uploaded_files)
        for name in names:
            st.markdown(f"""<div class="status-box">✅ <b>{name}</b></div>""", unsafe_allow_html=True)

    st.divider()
    st.markdown("### 🎯 Focus Area")
    focus = st.selectbox("Select Focus", ["General Business", "Sales & Revenue", "Marketing", "HR & Operations", "Finance"], label_visibility="collapsed")

    st.divider()
    if st.button("🗑️ Clear Chat"):
        st.session_state.messages = []
        st.session_state.doc_text = ""
        st.session_state.doc_names = []
        st.session_state.query_count = 0
        st.session_state.docs_uploaded = 0
        st.session_state.excel_df = None
        st.rerun()

    st.divider()
    st.markdown("### 🏢 Branding")
    company_name = st.text_input("Company Name", placeholder="Enter your company name...")
    if company_name:
        st.caption(f"Assistant for: **{company_name}**")

    st.divider()
    st.markdown("### 📧 Email Summary")
    email_to = st.text_input("Send to Email", placeholder="client@example.com", key="email_input")

    if st.button("📤 Send via Gmail"):
        if not email_to:
            st.warning("⚠️ Enter email address!")
        elif len(st.session_state.messages) <= 1:
            st.warning("⚠️ No chat history! Ask something first.")
        elif "@" not in email_to or "." not in email_to:
            st.warning("⚠️ Enter a valid email address!")
        else:
            with st.spinner("📧 Sending email..."):
                success, message = send_email_gmail(email_to, company_name)
                if success:
                    st.success(message)
                    st.balloons()
                else:
                    st.error(message)

    st.markdown("---")

    # -------------- DOWNLOAD CHAT SECTION --------------
    st.markdown("##### 📥 Or Download Chat")

    if len(st.session_state.messages) > 1:
        now = datetime.datetime.now()
        chat_text = f"""AI BUSINESS ASSISTANT - CHAT HISTORY
{'='*60}
Date: {now.strftime('%Y-%m-%d %H:%M:%S')}
Company: {company_name if company_name else 'N/A'}
Total Messages: {len(st.session_state.messages)}
Documents: {st.session_state.docs_uploaded}
{'='*60}
"""
        for i, msg in enumerate(st.session_state.messages, 1):
            role = "YOU" if msg['role'] == 'user' else "AI ASSISTANT"
            chat_text += f"\n{role} (Message {i}):\n{msg['content']}\n{'-'*60}\n"

        chat_text += f"\n{'='*60}\nGenerated by AI Business Assistant\n{'='*60}"

        st.download_button(
            label="💾 Download as TXT",
            data=chat_text.encode('utf-8'),
            file_name=f"AI_Chat_{now.strftime('%Y%m%d_%H%M%S')}.txt",
            mime="text/plain",
            use_container_width=True
        )
        # tanglish caption removed
    else:
        pass  # avoid indentation error

# ------------------- CHAT AREA -------------------
for i, message in enumerate(st.session_state.messages):
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

if prompt := st.chat_input("Ask about your document or any business question..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                system_prompt = f"You are a professional Business Assistant for {company_name}, focused on {focus}. Answer queries clearly and concisely."
                if st.session_state.doc_text:
                    system_prompt += f"\n\nDocument Content:\n{st.session_state.doc_text[:8000]}"

                response = client.chat.completions.create(
                    model="llama-3.1-8b-instant",
                    messages=[
                        {"role": "system", "content": system_prompt},
                        *[{"role": m["role"], "content": m["content"]} for m in st.session_state.messages]
                    ]
                )
                reply = response.choices[0].message.content
                st.markdown(reply)
                st.session_state.messages.append({"role": "assistant", "content": reply})
                st.session_state.query_count += 1
            except Exception as e:
                st.error(f"Error: {e}")